### ISSUE TITLE
How to use cmake with dreal built from sources

### ISSUE THREAD

**Issue by caballa** [dreal/dreal-cmake-example-project#4]
This example assumes that dreal is installed via homebrew.
However, I want to use dreal built from sources. My understanding is that the only difference would be to tell `pkg-config` where is the `dreal.pc` generated when I built dreal from sources.

The only `dreal.pc` I found is in `bazel-genfiles` directory and its content is:

```
prefix=HOMEBREW_PREFIX/opt/dreal
libdir=${prefix}/lib
includedir=${prefix}/include

Name: dReal
Description: SMT Solver for Nonlinear Theories
Version: 4.18.10.1
Requires: ibex, nlopt
Libs: -L${libdir} -ldreal
Cflags: -I${includedir}

```

The problem is `HOMEBREW_PREFIX` which is not defined. I'm not familiar with bazel at all. Where are installed the dreal header files and libraries so that i can set properly `HOMEBREW_PREFIX` ?

**Comment by soonho-tri** [comment]
`bazel build //:archive` will create `bazel-bin/archive.tar.gz` which includes headers and libraries. You still need to fix the `dreal.pc` file in it as it still has `HOMEBREW_PREFIX`.

**Comment by soonho-tri** [comment]
> This example assumes that dreal is installed via homebrew. However, I want to use dreal built from sources.

FYI, you can do `brew install dreal --HEAD` to build/use the latest version. It could make your workflow easier.

Anyway, please let me know if you need anything else.
